openapi: 3.0.3
info:
  title: Individuals Matching
  contact: {}
  version: 'P1.0'
  description: |
    # Overview
    Use this API to check HMRC records to find out information about an individual.

    The current version of the API lets you:
      
      * search for an individual using their name, date of birth and National Insurance number
      * get links you can use to view the individual's income and employments
    
    # Testing
    You can use the sandbox environment to [test this API](https://developer.service.hmrc.gov.uk/api-documentation/docs/testing).
    It does not support [stateful behaviour](https://developer.service.hmrc.gov.uk/api-documentation/docs/testing/stateful-behaviour).

    The Sandbox service for this API supports all the happy path responses and error scenarios described under Resources.

    You can set up a test individual for this API using the [Create Test User API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/api-platform-test-user/1.0#_create-a-test-user-which-is-an-individual_post_accordion).

servers:
- url: https://api.service.hmrc.gov.uk/
  variables: {}
paths:
  /individuals/matching/:
    post:
      tags:
      - individuals
      summary: Match an individual's details against HMRC data
      description: |-
        This resource is used to match an individual's first name, last name, date of birth and National Insurance Number (NINO) against HMRC’s records. On a successful match, a matchId is returned.
        
        The following set of criteria must all be met for a successful match of the data provided, against HMRC’s records:
        
        |Parameter|Match Criteria
        |---|---
        |firstName|First character must be identical; all remaining characters are ignored
        |lastName|First three characters must be identical; all remaining characters are ignored
        |nino|All characters must be identical
        |dateOfBirth|All characters must be identical

      operationId: Matchanindividual'sdetailsagainstHMRCdata
      parameters:
      - name: Authorization
        in: header
        description: OAuth 2.0 Bearer Token with the read:individuals-matching scope.
        required: true
        style: simple
        schema:
          type: string
          example: Bearer <BEARER_TOKEN>
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/IndividualsMatchingrequest'
              - example:
                  firstName: Amanda
                  lastName: Joseph
                  nino: NA000799C
                  dateOfBirth: 1960-01-15
            example:
              firstName: Amanda
              lastName: Joseph
              nino: NA000799C
              dateOfBirth: 1960-01-15
        required: true
      responses:
        '200':
          description: The available resources to retrieve the matched individual's details
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/IndividualsMatchingresponse'
                - example:
                    _links:
                      individual:
                        href: /individuals/matching/57072660-1df9-4aeb-b4ea-cd2d7f96e430
                        name: GET
                        title: Individual Details
                      self:
                        href: /individuals/matching/
              example:
                _links:
                  individual:
                    href: /individuals/matching/57072660-1df9-4aeb-b4ea-cd2d7f96e430
                    name: GET
                    title: Individual Details
                  self:
                    href: /individuals/matching/
        '400':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/errorResponse400'
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
        '403':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/errorResponse403'
              examples:
                Forbidden:
                  description: The individual's details provided did not match with HMRC’s records
                  value:
                    code: MATCHING_FAILED
      deprecated: false
      security:
        - userRestricted: [ "read:individuals-matching" ]
  /individuals/matching/{matchId}:
    get:
      tags:
      - individuals
      summary: Retrieve matched individual's details
      description: |-
        Enables access to the functionality provided for matched individuals.

        The matchId is a short-lived UUID, typically valid for several hours. If the matchId has expired, subsequent requests will return a 404 error.
        #### Authorisation

        This endpoint is [user-restricted](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints) and requires `read:individuals-matching` header containing an OAUTH 2.0 Bearer Token.

        See also [fraud prevention](https://developer.service.hmrc.gov.uk/guides/fraud-prevention/).

      operationId: Retrievematchedindividual'sdetails
      parameters:
      - name: matchId
        in: path
        description: A short-lived UUID, typically valid for several hours
        required: true
        style: simple
        schema:
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
      - name: Authorization
        in: header
        description: OAuth 2.0 Bearer Token with the read:individuals-matching scope.
        required: true
        style: simple
        schema:
          type: string
          example: Bearer <BEARER_TOKEN>
      - name: CorrelationId
        in: header
        description: A CorrelationId provided by you.
        required: true
        style: simple
        schema:
          type: string
          example: 188e9400-b636-4a3b-80ba-230a8c72b92a
      responses:
        '200':
          description: The individual's details for the given match id
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/IndividualsMatchingresponse1'
                - example:
                    _links:
                      income:
                        href: /individuals/income/?matchId=57072660-1df9-4aeb-b4ea-cd2d7f96e430
                        name: GET
                        title: View individual's income
                      employments:
                        href: /individuals/employments/?matchId=57072660-1df9-4aeb-b4ea-cd2d7f96e430
                        name: GET
                        title: View individual's employments
                      self:
                        href: /individuals/matching/57072660-1df9-4aeb-b4ea-cd2d7f96e430
                    individual:
                      firstName: Amanda
                      lastName: Joseph
                      nino: NA000799C
                      dateOfBirth: 1960-01-15
              example:
                _links:
                  income:
                    href: /individuals/income/?matchId=57072660-1df9-4aeb-b4ea-cd2d7f96e430
                    name: GET
                    title: View individual's income
                  employments:
                    href: /individuals/employments/?matchId=57072660-1df9-4aeb-b4ea-cd2d7f96e430
                    name: GET
                    title: View individual's employments
                  self:
                    href: /individuals/matching/57072660-1df9-4aeb-b4ea-cd2d7f96e430
                individual:
                  firstName: Amanda
                  lastName: Joseph
                  nino: NA000799C
                  dateOfBirth: 1960-01-15
        '404':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/errorResponse404'
              examples:
                NotFound:
                  description: Not found
                  value:
                    code: NOT_FOUND
      deprecated: false
      security:
        - userRestricted: [ "read:individuals-matching" ]
components:
  securitySchemes:
    userRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating User-restricted API requests
        
        See also [fraud prevention](https://developer.service.hmrc.gov.uk/guides/fraud-prevention/).
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes: {
            read:individuals-matching: Match individual from their details,
            read:individuals-matching-laa-c1: Scope for LAA use case 1 to match an individual from their details,
            read:individuals-matching-laa-c2: Scope for LAA use case 2 to match an individual from their details,
            read:individuals-matching-laa-c3: Scope for LAA use case 3 to match an individual from their details,
            read:individuals-matching-laa-c4: Scope for LAA use case 4 to match an individual from their details,
            read:individuals-matching-hmcts-c2: Scope for HMCTS use case 2 to match an individual from their details,
            read:individuals-matching-hmcts-c3: Scope for HMCTS use case 3 to match an individual from their details,
            read:individuals-matching-hmcts-c4: Scope for HMCTS use case 4 to match an individual from their details,
            read:individuals-matching-lsani-c1: Scope for LSANI use case 1 to match an individual from their details,
            read:individuals-matching-lsani-c3: Scope for LSANI use case 3 to match an individual from their details,
            read:individuals-matching-nictsejo-c4: Scope for NICTSEJO use case 4 to match an individual from their details,
            read:individuals-matching-ho-rp2: Scope for HO RP2 to match an individual from their details,
            read:individuals-matching-ho-ecp: Scope for HO ECP to match an individual from their details,
            read:individuals-matching-ho-v2: Scope for HO that replicates the v1 version of the same scope,
            assigned: An OAuth 2.0 Bearer Token with the scopes you have been assigned
          }
  schemas:
    errorResponse404:
      title: errorResponse
      required:
      - code
      type: object
      properties:
        code:
          type: string
          description: Code always has value of "NOT_FOUND"
      example:
        code: NOT_FOUND
    errorResponse400:
      title: errorResponse
      required:
        - code
      type: object
      properties:
        code:
          type: string
          description: Code always has value of "INVALID_REQUEST"
      example:
        code: INVALID_REQUEST
    errorResponse403:
      title: errorResponse
      required:
        - code
      type: object
      properties:
        code:
          type: string
          description: Code always has value of "MATCHING_FAILED"
      example:
        code: MATCHING_FAILED
    Employments:
      title: Employments
      required:
      - href
      type: object
      properties:
        href:
          type: string
          example: /individuals/employments/?matchId=57072660-1df9-4aeb-b4ea-cd2d7f96e430
        name:
          type: string
          example: GET
        title:
          type: string
          example: View individual's employments
      description: The URI for the resource to get the individual's employments.
    Income:
      title: Income
      required:
      - href
      type: object
      properties:
        href:
          type: string
          example: /individuals/income/?matchId=57072660-1df9-4aeb-b4ea-cd2d7f96e430
        name:
          type: string
          example: GET
        title:
          type: string
          example: View individual's income
      description: The URI for the resource to get the individual's income.
    Individual:
      title: Individual
      required:
      - href
      type: object
      properties:
        href:
          type: string
          example: /individuals/matching/57072660-1df9-4aeb-b4ea-cd2d7f96e430
        name:
          type: string
          example: GET
        title:
          type: string
          example: Individual Details
      description: The URI for the resource to get the individual's information.
    Individual1:
      title: Individual1
      required:
      - firstName
      - lastName
      - nino
      - dateOfBirth
      type: object
      properties:
        firstName:
          type: string
          description: The individual's first name
        lastName:
          type: string
          description: The individual's last name
        nino:
          type: string
          description: The individual's national insurance number
        dateOfBirth:
          type: string
          description: The individual's date of birth
          format: date
      description: The matched individual.
    IndividualsMatchingrequest:
      title: IndividualsMatchingrequest
      required:
      - firstName
      - lastName
      - dateOfBirth
      - nino
      type: object
      properties:
        firstName:
          maxLength: 35
          minLength: 1
          type: string
          description: Individual's first name. Must only contain letters, `, -, and '
        lastName:
          maxLength: 35
          minLength: 1
          type: string
          description: Individual's first name. Must only contain letters, `, -, and '
        dateOfBirth:
          type: string
          description: The individual's date of birth
          format: date
        nino:
          type: string
          description: Individual's national insurance number
      description: Individual matching request
    IndividualsMatchingresponse:
      title: IndividualsMatchingresponse
      required:
      - _links
      type: object
      properties:
        _links:
          $ref: '#/components/schemas/Links'
      description: Matched Individual
    IndividualsMatchingresponse1:
      title: IndividualsMatchingresponse1
      required:
      - _links
      - individual
      type: object
      properties:
        _links:
          $ref: '#/components/schemas/Links1'
        individual:
          allOf:
          - $ref: '#/components/schemas/Individual1'
          - description: The matched individual.
      description: Individuals Matching
    Links:
      title: Links
      required:
      - individual
      - self
      type: object
      properties:
        individual:
          allOf:
          - $ref: '#/components/schemas/Individual'
          - description: The URI for the resource to get the individual's information.
        self:
          allOf:
          - $ref: '#/components/schemas/Self'
          - description: The URI to this resource
    Links1:
      title: Links1
      required:
      - income
      - employments
      - self
      type: object
      properties:
        income:
          allOf:
          - $ref: '#/components/schemas/Income'
          - description: The URI for the resource to get the individual's income.
        employments:
          allOf:
          - $ref: '#/components/schemas/Employments'
          - description: The URI for the resource to get the individual's employments.
        self:
          allOf:
          - $ref: '#/components/schemas/Self'
          - description: The URI to this resource
    Self:
      title: Self
      required:
      - href
      type: object
      properties:
        href:
          type: string
          example: /individuals/matching/
      description: The URI to this resource
tags:
- name: individuals
  description: ''
